### ISSUE TITLE
Unit of measure to Ingredients input

### ISSUE THREAD

**Issue by IonaHS** [tomhamiltonstubber/salsa-verde#241]
Can you add the unit of measure between the 'quantity' and 'batch code' boxes

**Comment by IonaHS** [comment]
![Screenshot 2024-01-15 at 14 34 59](https://github.com/tomhamiltonstubber/salsa-verde/assets/156119305/fe976059-3109-4723-b61f-ec62075060be)

**Comment by IonaHS** [comment]
'total weight' is automatically calculated by the system

**Comment by tomhamiltonstubber** [comment]
When an Ingredient Type is added, the user chooses the unit of measurement that will be used for that product type. As I see it, blackberries are always measured in Kilograms, vinegar measured in litres etc.

**Comment by IonaHS** [comment]
That sounds good.
